name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NPM
        uses: ./.github/actions/setup-npm

      - name: Run ESLint
        run: npm run lint